language: node_js
node_js:
- "8.9.0"
branches:
  only:
   - master
   - dev

before_install:
- openssl aes-256-cbc -K $encrypted_a544a21591f6_key -iv $encrypted_a544a21591f6_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- export TZ='Asia/Shanghai'
- npm install -g hexo
- npm install -g hexo-cli
- npm install hexo-wordcount --save
- npm install hexo-fs --save
- npm install 
- ls node_modules/hexo-generator-index/
- cp .travis/generator.js ./node_modules/hexo-generator-index/lib/
# ------------------------------------------------
# 设置github账户信息 注意修改成自己的信息
# ------------------------------------------------
- git config --global user.name "Tivon.Feng"
- git config --global user.email "tivonfeng@gmail.com"
# ------------------------------------------------
# github仓库操作  注意将仓库修改成自己的
# ------------------------------------------------
#- sed -i'' "s~git@github.com:xuezhisd/xuezhisd.github.io.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/xuezhisd/xuezhisd.github.io.git~" _config.yml
# 安装依赖组件
install:
    #- npm install
# 执行的命令
script:
- ssh -T git@git.coding.net
- hexo clean
- hexo generate
# 执行的成功后执行
after_success:
- hexo deploy
