
language:node_js
node_js:
- "4"
branches:
    only:
     - master

before_install:
- openssl aes-256-cbc -K $encrypted_a544a21591f6_key -iv $encrypted_a544a21591f6_iv in id_rsa.enc -out id_rsa -d
- export TZ='Asia/Shanghai'
- npm install -g hexo
- npm install -g hexo-cli
- npm install 
# ------------------------------------------------
# 设置github账户信息 注意修改成自己的信息
# ------------------------------------------------
#- git config --global user.name "xuezhisd"
#- git config --global user.email xuezhi@126.com
# ------------------------------------------------
# github仓库操作  注意将仓库修改成自己的
# ------------------------------------------------
#- sed -i'' "s~git@github.com:xuezhisd/xuezhisd.github.io.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/xuezhisd/xuezhisd.github.io.git~" _config.yml
# 安装依赖组件
install:
- npm install
# 执行的命令
script:
- hexo clean
- hexo generate
# 执行的成功后执行
after_success:
- hexo deploy
